# Generated by Django 2.0 on 2019-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190923_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(max_length=255, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
